name: wisequotes
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  http: ^1.1.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  share_plus: ^7.2.1
  device_preview: ^1.1.0
  flutter_tts: ^3.8.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_app.png"
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
